package org.CandyLand;

public enum CardType {
    SINGLE_RED,
    SINGLE_YELLOW,
    SINGLE_BLUE,
    SINGLE_GREEN,
    SINGLE_ORANGE,
    DOUBLE_RED,
    DOUBLE_YELLOW,
    DOUBLE_BLUE,
    DOUBLE_GREEN,
    DOUBLE_ORANGE,
    SKIP_TURN,
    GO_TO_MIDDLE,
    UPSIDEDOWN,
    EMPTY_DISCARD,
    EMPTY_DRAW
}